config/routes.rb
Rails.application.routes.draw do
  root 'work_items#index'
  resources :locations
  resources :work_items
  resources :users

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
  has_many :work_items
  
  validates_presence_of :address1, :city, :zip
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location
  has_many :work_items
  
  validates_uniqueness_of :email
  validates_presence_of :fname, :lname, :email, :location_id
end

app/models/work_item.rb
class WorkItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  
  validates_presence_of :user_id, :location_id, :priority, :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address1, :address2, :city, :zip, :phone_number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # skip_before_action :verify_authentication_token

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :phone, :location_id, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/work_items_controller.rb
class WorkItemsController < ApplicationController
  before_action :set_work_item, only: [:show, :edit, :update, :destroy]

  # GET /work_items
  # GET /work_items.json
  def index
    @work_items = WorkItem.all
  end

  # GET /work_items/1
  # GET /work_items/1.json
  def show
  end

  # GET /work_items/new
  def new
    @work_item = WorkItem.new
  end

  # GET /work_items/1/edit
  def edit
  end

  # POST /work_items
  # POST /work_items.json
  def create
    @work_item = WorkItem.new(work_item_params)

    respond_to do |format|
      if @work_item.save
        format.html { redirect_to @work_item, notice: 'Work item was successfully created.' }
        format.json { render :show, status: :created, location: @work_item }
      else
        format.html { render :new }
        format.json { render json: @work_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_items/1
  # PATCH/PUT /work_items/1.json
  def update
    respond_to do |format|
      if @work_item.update(work_item_params)
        format.html { redirect_to @work_item, notice: 'Work item was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_item }
      else
        format.html { render :edit }
        format.json { render json: @work_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_items/1
  # DELETE /work_items/1.json
  def destroy
    @work_item.destroy
    respond_to do |format|
      format.html { redirect_to work_items_url, notice: 'Work item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_item
      @work_item = WorkItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_item_params
      params.require(:work_item).permit(:priority, :description, :picture, :user_id, :location_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>C2040HousingServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>Zip</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address1 %></td>
        <td><%= location.address2 %></td>
        <td><%= location.city %></td>
        <td><%= location.zip %></td>
        <td><%= location.phone_number %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address1:</strong>
  <%= @location.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @location.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @location.zip %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @location.phone_number %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
	<div class="field">
		<%= f.label :location_id %><br>
		<%= f.number_field :location_id %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
	<strong>Phone:</strong>
	<%= @user.phone %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/work_items/_form.html.erb
<%= form_for(@work_item) do |f| %>
  <% if @work_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_item.errors.count, "error") %> prohibited this work_item from being saved:</h2>

      <ul>
      <% @work_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_items/edit.html.erb
<h1>Editing Work Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_item %> |
<%= link_to 'Back', work_items_path %>

app/views/work_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Work Items</h1>

<table>
  <thead>
    <tr>
      <th>Priority</th>
      <th>Description</th>
      <th>Picture</th>
      <th>User</th>
			<th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_items.each do |work_item| %>
      <tr>
        <td><%= work_item.priority %></td>
        <td><%= work_item.description %></td>
        <td><%= work_item.picture %></td>
        <td><%= work_item.user_id %></td>
				<td><%= work_item.location_id %></td>
        <td><%= work_item.status %></td>
        <td><%= link_to 'Show', work_item %></td>
        <td><%= link_to 'Edit', edit_work_item_path(work_item) %></td>
        <td><%= link_to 'Destroy', work_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work item', new_work_item_path %>

app/views/work_items/new.html.erb
<h1>New Work Item</h1>

<%= render 'form' %>

<%= link_to 'Back', work_items_path %>

app/views/work_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Priority:</strong>
  <%= @work_item.priority %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_item.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @work_item.picture %>
</p>

<p>
  <strong>User:</strong>
  <%= @work_item.user_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @work_item.location_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @work_item.status %>
</p>

<%= link_to 'Edit', edit_work_item_path(@work_item) %> |
<%= link_to 'Back', work_items_path %>